### ISSUE TITLE
ScopedCssBaseline doesn't work

### ISSUE THREAD

**Issue by FilipKittnar** [cca-io/rescript-mui#181]
Hello,
When trying to use the ScopedCssBaseline module, I get runtime error:

> Attempted import error: 'ScopedCssBaseline' is not exported from '@material-ui/core' (imported as 'Core').

**Comment by FilipKittnar** [comment]
This seemed to help:

```
@react.component @module("@material-ui/core/ScopedCssBaseline")
external make: (
  ~children: React.element=?,
  ~classes: Mui.ScopedCssBaseline.Classes.t=?,
  ~className: string=?,
  ~id: string=?,
  ~style: ReactDOM.Style.t=?,
  ~key: string=?,
  ~ref: ReactDOM.domRef=?,
) => React.element = "default"
```

**Comment by fhammerschmidt** [comment]
The problem here is, that it is not re-exported in [this file](https://github.com/mui-org/material-ui/blob/v4.12.3/packages/material-ui/src/index.js). 

They only fixed that in v5, unfortunately: https://github.com/mui-org/material-ui/pull/21869/files

**Comment by cknitt** [comment]
Maybe we can patch the MUI sources before the code generation step?

**Comment by fhammerschmidt** [comment]
This is fixed in version 5. Closing...
