### ISSUE TITLE
Autocomplete multiple value type error

### ISSUE THREAD

**Issue by efirvida** [cca-io/rescript-mui#201]
Hi, if I try to set the value of a multiple field, this trough a error sayung that the value prop is needs a **_type_** but I'm giving an **_array \<type\>_**, so there is something missing in the type of the value prop.

Using the provided example:

```javascript

type top100 = {
  title: string,
  year: int,
}

let top100Films = [
  {title: "The Shawshank Redemption", year: 1994},
  {title: "The Godfather", year: 1972},
  ...
]

<Mui.Autocomplete
    id="combo-box-demo"
    options=top100Films
    getOptionLabel={option => option.title}
    fullWidth=true
    multiple=true               // multiple
    value=top100Films     // values
    renderInput={params => {
      let props = params->Mui.Autocomplete.renderInputParamsToTextFieldProps
      <Mui.TextField {...props} label={React.string({"Combo box"})} variant=Outlined />
    }}
  />
}
```

give:
```

  This has type: array<top100>
  Somewhere wanted: top100
```

**Comment by fhammerschmidt** [comment]
I'll try to refine the Autocomplete bindings a bit soon. Maybe even to the same pattern as the [Slider/Slider.Ranged](https://github.com/cca-io/rescript-mui/blob/master/packages/rescript-mui-material/src/components/Slider.res#L313-L321).

Which means to export both a `Autocomplete` and `Autocomplete.Multiple`. I cannot think of a use-case where you want to dynamically change from the one to the other anyway.

**Comment by fhammerschmidt** [comment]
Published a new version with some changes. Check out the examples how to use them: https://github.com/cca-io/rescript-mui/blob/master/examples/src/examples/ExampleAutocomplete.res
