### ISSUE TITLE
Release X-Datepickers to npm?

### ISSUE THREAD

**Issue by TomiS** [cca-io/rescript-mui#206]
Just ship it. :wink:

**Comment by TomiS** [comment]
Ok, maybe it's a bit early for that after all.

**Comment by fhammerschmidt** [comment]
Current bindings are based on the complex setup of TS types in Mui-X-DatePickers. I have a bunch of easier to use (but also incomplete) ones locally. I will try to publish them by the end of the year. As well as a real release of mui and lab.
