### ISSUE TITLE
Fab component is missing ButtonBase props

### ISSUE THREAD

**Issue by DrMorbid** [cca-io/rescript-mui#208]
Hello,
`onClick` cannot be used as a prop for the `Fab` component. When I hardcode it to the transpiled `.js` file, everything works.
When you look at the [doc page](https://mui.com/material-ui/api/fab/), you can find a sentence:

> Props of the [ButtonBase](https://mui.com/material-ui/api/button-base/) component are also available.

**Comment by fhammerschmidt** [comment]
Thanks for reporting!
I fixed it here: https://github.com/cca-io/rescript-mui/commit/872dc23ac849ac2234656f6b7e90c33d568a007f and also published a new version.

**Comment by DrMorbid** [comment]
Thanks a lot for such a quick fix!
Not sure it's completely correct though. It seems that `onClick` is in type `clickablePropsWithOnClick` and not `clickableProps`.

**Comment by fhammerschmidt** [comment]
Argh! I set up a trap for myself here. Fixed it now and published another version. Sorry.
