### ISSUE TITLE
Usage of props with "unknown" type.

### ISSUE THREAD

**Issue by chrischen** [cca-io/rescript-mui#210]
Are there any examples of usage of props that are typed as "unknown" such as this:

`component?: Mui.OverridableComponent.t<unknown>,`

Or is this just a placeholder for incomplete bindings? Are we supposed to use %raw() in these cases?

**Comment by fhammerschmidt** [comment]
It's more like when the props don't actually matter. For instance because you want to use a `<h1>`, instead of the default: 

```reason
<Typography component={OverridableComponent.string("h1")} variant=H6 noWrap=true>
  {"Dashboard"->React.string}
</Typography>
```

**Comment by chrischen** [comment]
How would I use it with OverridableComponent.component? When I passed in a React component it would give a type error saying it didn't match with "unknown."

**Comment by fhammerschmidt** [comment]
Hmm, I will add a `componentWithUnknownProps` function as well then.

For now you can use this instead:
```res
external componentWithUnknownProps: React.component<'props> => Mui.OverridableComponent.t<unknown> =
  "%identity"
```

**Comment by fhammerschmidt** [comment]
Just published a new version and added an example on how to use it: https://github.com/cca-io/rescript-mui/blob/master/examples/src/examples/ExampleComponentOverride.res
